# 知识库模块配置
knowledge-base:
  # 基础配置
  config:
    # 默认分页大小
    default-page-size: 20
    # 最大分页大小
    max-page-size: 100
    # 树形结构最大深度
    max-tree-depth: 10
    # 单个知识库最大文档数
    max-documents-per-kb: 10000
    # 知识库名称最大长度
    max-kb-name-length: 100
    
  # 权限配置
  permission:
    # 默认权限继承
    default-inherit-parent: true
    # 权限缓存时间（秒）
    permission-cache-ttl: 3600
    # 是否启用权限缓存
    enable-permission-cache: true
    # 权限检查超时时间（毫秒）
    permission-check-timeout: 5000
    
  # 嵌入配置
  embedding:
    # 默认嵌入模型
    default-model: "text-embedding-ada-002"
    # 支持的嵌入模型
    supported-models:
      - "text-embedding-ada-002"
      - "text-embedding-3-small"
      - "text-embedding-3-large"
      - "bge-large-zh"
      - "m3e-base"
    # 默认分块配置
    chunking:
      default-size: 1000
      default-overlap: 200
      max-size: 4000
      min-size: 100
    # 嵌入任务配置
    task:
      # 并发嵌入任务数
      max-concurrent-tasks: 5
      # 任务超时时间（分钟）
      task-timeout-minutes: 30
      # 重试次数
      max-retry-count: 3
      # 重试间隔（秒）
      retry-interval-seconds: 60
    # 向量存储配置
    vector-store:
      # 批量插入大小
      batch-insert-size: 100
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      
  # 审计配置
  audit:
    # 是否启用审计
    enabled: true
    # 审计日志保留天数
    retention-days: 365
    # 敏感操作是否必须审计
    require-sensitive-audit: true
    # 异步记录审计日志
    async-logging: true
    # 审计队列大小
    audit-queue-size: 1000
    
  # 文件配置
  file:
    # 支持的文档类型
    supported-types:
      - "pdf"
      - "doc"
      - "docx"
      - "txt"
      - "md"
      - "json"
      - "xml"
      - "csv"
      - "html"
      - "htm"
      - "ppt"
      - "pptx"
      - "xls"
      - "xlsx"
    # 单个文档最大大小（MB）
    max-file-size: 50
    # 文档预览最大长度
    max-preview-length: 5000
    
  # 与upload模块集成配置
  upload-integration:
    # 是否启用文件上传集成
    enabled: true
    # 自动创建文档节点
    auto-create-document: true
    # 文件权限检查
    file-permission-check: true
    # 支持的文件来源
    supported-sources:
      - "LOCAL"
      - "MINIO"
    # 文件访问超时时间（毫秒）
    file-access-timeout: 10000
    
  # 缓存配置
  cache:
    # 知识库列表缓存时间（秒）
    kb-list-cache-ttl: 1800
    # 文档树缓存时间（秒）
    document-tree-cache-ttl: 3600
    # 统计数据缓存时间（秒）
    stats-cache-ttl: 900
    # 权限缓存时间（秒）
    permission-cache-ttl: 1800
    
  # 性能配置
  performance:
    # 异步处理线程池大小
    async-pool-size: 10
    # 批量操作最大大小
    max-batch-size: 1000
    # 查询超时时间（毫秒）
    query-timeout: 30000
    
  # 监控配置
  monitoring:
    # 是否启用性能监控
    enable-metrics: true
    # 慢查询阈值（毫秒）
    slow-query-threshold: 5000
    # 是否记录详细日志
    detailed-logging: false
    
  # 安全配置
  security:
    # 数据脱敏
    data-masking:
      # 是否启用敏感数据脱敏
      enabled: true
      # 脱敏字段
      mask-fields:
        - "password"
        - "token"
        - "secret"
    # API限流
    rate-limit:
      # 是否启用限流
      enabled: true
      # 每分钟请求数限制
      requests-per-minute: 1000
      # 每小时请求数限制
      requests-per-hour: 10000

# Spring Data JPA 配置
spring:
  jpa:
    # 自动创建表结构
    hibernate:
      ddl-auto: update
    # 显示SQL
    show-sql: false
    # 数据库方言
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 批量操作配置
        jdbc:
          batch_size: 50
        # 二级缓存配置
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

# 缓存配置
cache:
  type: caffeine
  caffeine:
    spec: maximumSize=10000,expireAfterAccess=1h

# 日志配置
logging:
  level:
    cn.mojoup.ai.kb: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN 