# 文件上传模块配置
app:
  upload:
    # 存储类型: local/minio
    storage-type: local
    # 单个文件最大大小 (10MB)
    max-file-size: 10485760
    # 最大请求大小 (50MB)
    max-request-size: 52428800
    # 允许的文件扩展名
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - txt
      - md
      - json
      - xml
      - csv
      - zip
      - rar
      - 7z
      - tar
      - gz
    # 本地存储配置
    local:
      # 存储根目录
      root-path: ./uploads
      # URL前缀
      url-prefix: /files
      # 是否按日期分目录
      date-folder: true
    # MinIO存储配置
    minio:
      # 服务端点
      endpoint: http://localhost:9000
      # 访问密钥
      access-key: minioadmin
      # 秘密密钥
      secret-key: minioadmin
      # 默认存储桶
      bucket-name: uploads
      # 是否自动创建存储桶
      auto-create-bucket: true
      # URL过期时间（秒）7天
      url-expiry: 604800

# Spring配置
spring:
  servlet:
    multipart:
      # 启用multipart上传
      enabled: true
      # 单个文件最大大小
      max-file-size: 10MB
      # 最大请求大小
      max-request-size: 50MB
      # 文件大小阈值，当大于这个阈值时将写入到临时文件中
      file-size-threshold: 1MB
      # 上传文件的临时目录
      location: ${java.io.tmpdir}

# Spring Security配置（开发环境）
security:
  user:
    name: admin
    password: admin123
    roles: ADMIN

# 日志配置
logging:
  level:
    cn.mojoup.ai.upload: INFO
    com.alibaba.druid: INFO
    io.minio: INFO
    org.springframework.security: DEBUG

# 数据库配置
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:postgresql://localhost:5432/spring_ai_app
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver
  
  # Druid连接池配置
  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,slf4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
    # Druid监控配置
    web-stat-filter:
      enabled: true
      url-pattern: "/*"
      exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    stat-view-servlet:
      enabled: true
      url-pattern: "/druid/*"
      allow: 127.0.0.1
      reset-enable: false
      login-username: admin
      login-password: 123456

# JPA配置
jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      jdbc:
        batch_size: 20
      order_inserts: true
      order_updates: true 