spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    druid:
      master:
        url: jdbc:postgresql://localhost:5431/springai
        username: springai_user
        password: springai_pwd
      slave:
        enabled: false
        url:
        username:
        password:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
      filter:
        stat:
          enabled: false
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  ai:
    openai:
      base-url: http://localhost:3000
      api-key: sk-mvsqwhucav6MLoOo6f67992320Df42C8Ba1f5bE9B36fE096
      chat:
        base-url: http://localhost:3000
        api-key: sk-mvsqwhucav6MLoOo6f67992320Df42C8Ba1f5bE9B36fE096
        options:
          model: llama3.1:8b
          temperature: 0.7
          max-tokens: 4096
          top-p: 1.0
    vectorstore:
      pgvector:
        enabled: true
        datasource:
          url: jdbc:postgresql://localhost:5432/vector_db
          username: springai_user
          password: springai_pwd
          driver-class-name: org.postgresql.Driver
        database: springai
        schema: public
        table: vector_store
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine
        initialize-schema: true
        hnsw:
          m: 16
          ef-construction: 40
          ef-search: 40
